sudo: false
language: generic
matrix:
  include:
    - os: linux
      language: python
      python: "3.5"
    - os: linux
      language: python
      python: "3.6"
    - os: osx
      language: generic
      env: TRAVIS_PYTHON_VERSION="3.5.5"
    - os: osx
      language: generic
      env: TRAVIS_PYTHON_VERSION="3.6.4"

before_install:
  - |
    set -e
    if [[ "${TRAVIS_OS_NAME}" == "osx" ]]; then
      brew update
      brew install pyenv || brew upgrade pyenv
      pyenv install "${TRAVIS_PYTHON_VERSION}"
      export PATH="$HOME/.pyenv/versions/${TRAVIS_PYTHON_VERSION}/bin:${PATH}"
    fi
    set +e

install:
  - pip install -U pip
  - pip install -U -r dev_requirements.txt

script:
  - TEST_PACKAGING=1 python -m coverage run --branch --source . -m unittest discover --verbose

after_success:
  - python -m coverage report --show-missing
  - codecov
  - python -m pylint --load-plugins=pylint.extensions.mccabe --docstring-min-length 5 --no-docstring-rgx "^(test)?_|.*Tests$" --unsafe-load-any-extension y --output-format colorized  --reports y $(find . -name "*.py")

notifications:
  slack:
    secure: "uUjhlldJ7fk0wO1SW0/unhIMzXpXrG2fjj0TekMBhKwve3w/x1IB/qQdPS9FXLQs90IALt37VpEjUFQTZWvPShDpX7QfD/xscnZ+djLCRoqFzwf4dCj0sDBprwuBC+IcQFiBxAkpndzjOEJkAX2M/Ua9nQSLABYH0/+bd/y7se+m/fVVO5PvQY2A0w6ySETkAK5wB4FqVdndBpDgD0RrW78+rwRowuK/84DigFjhlccYWcBGfZmX2Qm1EMsyOY1xidFaprIvE6Jhq+XYDQEI/kObQudGSd51zmdvSen7c1+pWie0ZVajzyctAb43JlQme2rGgPscc8zX7Gn/t4HK45yV8oZNgiPaVHnxtW0P3wpjN5TePOsesWT5QPVfh8czwsbn7Iy+ZWpeX9mMvgOyEguaKRF72/02dlBL8m0cmobV99YUcNTqd5tEQX5/kBG3OrHdVglNYh2z7tx6ZbZPEN92uA9YR7gBid4bv8nWGP9Dv6zhcHMmj1gcadOpRbAKVDnc3IGTS9eLmH3LRFu+rt07+VE4XW/xwVRUjq8PTyB89qSi6sVURoPeMT60szVx5wqqaQojWWsWQDU4GVPEjS+sXm+kYgr3AUazWdHIaJ97NFPOxmGl0+gQEyiFg4b67APYA0eR6AMVc/iwt9TWMRxEoxju3d9azLd8pGwuaP0="
  email: false
